{
 "title": "11DecTrial",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total HTTP requests",
   "type": "stat",
   "description": "Total incoming HTTP requests",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (fastapi_model_http_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In progress requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (fastapi_inprogress)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP requests by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "fastapi_model_http_requests_total{job=\"fastapi\"}",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Logistic Regression output",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_model_model_output_bucket{model_type=\"LogisticRegression\", le!=\"+Inf\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "SVC output",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_model_model_output_bucket{model_type=\"SVC\", le!=\"+Inf\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Classification latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(le) (rate(fastapi_model_http_request_duration_seconds_bucket{handler=\"/models/{type}\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}