{
 "title": "Grafana Dashboard",
 "description": "Example Dashboard for the SE4AI course",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total number of HTTP requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fastapi_model_http_requests_total{})"
    }
   ]
  },
  {
   "title": "Type of HTTP requests",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (fastapi_model_http_requests_total{}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Current in-progress requests",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(fastapi_inprogress)" }
   ]
  },
  {
   "title": "Request rate in the last minute",
   "type": "gauge",
   "description": "Per-second rate for all time series with the `http_requests_total` metric name, as measured over the last minute",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fastapi_model_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "HTTP requests rate in the last 30s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(fastapi_model_http_requests_total{}[$__interval]))",
     "legendFormat": "HTTP requests"
    }
   ]
  },
  {
   "title": "Endpoint requests in the last 30s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(fastapi_model_http_requests_total[$__interval]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Model Type",
   "type": "piechart",
   "description": "Portion of classification requests directed to each model type.",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_model_model_output_count",
     "legendFormat": "{{model_type}}"
    }
   ]
  },
  { "title": "Classification output values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "SVC",
   "type": "bargauge",
   "description": "Occurrence of classification output values for the SVC model",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{le=~\"0\\\\.0|1\\\\.0|2\\\\.0\",model_type=\"SVC\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Logistic Regression",
   "type": "bargauge",
   "description": "Occurrence of classification output values for the LogisticRegression model",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{le=~\"0\\\\.0|1\\\\.0|2\\\\.0\",model_type=\"LogisticRegression\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}